import React from 'react';
import { Link } from 'react-router-dom';
import { 
  FileText, TrendingUp, Sparkles, ChevronRight, 
  Zap, BrainCircuit, Target, Clock, ShieldCheck
} from 'lucide-react';

const ToolsPage = () => {
  const tools = [
    {
      id: 'lab-gen',
      title: 'Auto Lab Report',
      description: 'Generate perfectly formatted, PDF-ready lab reports in seconds. Stop wasting hours on manual formatting.',
      icon: <FileText size={36} />,
      link: '/tools/lab-gen',
      color: 'from-emerald-400 to-teal-600',
      glow: 'group-hover:bg-emerald-500/20',
      border: 'group-hover:border-emerald-500/50',
      shadow: 'hover:shadow-[0_0_50px_-12px_rgba(16,185,129,0.4)]',
      badge: 'Time Saver',
      badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
    },
    {
      id: 'ai-roadmap',
      title: 'AI Career Roadmap',
      description: 'Get a personalized, step-by-step career path generated by advanced AI based on your current skills and CGPA.',
      icon: <BrainCircuit size={36} />,
      link: '/roadmaps',
      color: 'from-purple-400 to-indigo-600',
      glow: 'group-hover:bg-purple-500/20',
      border: 'group-hover:border-purple-500/50',
      shadow: 'hover:shadow-[0_0_50px_-12px_rgba(168,85,247,0.4)]',
      badge: 'AI Powered',
      badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20'
    },
    {
      id: 'cgpa-tracker',
      title: 'CGPA Tracker & Predictor',
      description: 'Log your semesters, track your academic growth, and mathematically predict the grades needed to hit your target CGPA.',
      icon: <TrendingUp size={36} />,
      link: '/tools/cgpa',
      color: 'from-cyan-400 to-blue-600',
      glow: 'group-hover:bg-cyan-500/20',
      border: 'group-hover:border-cyan-500/50',
      shadow: 'hover:shadow-[0_0_50px_-12px_rgba(6,182,212,0.4)]',
      badge: 'Essential',
      badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20'
    }
  ];

  return (
    <div className="min-h-screen pt-28 pb-20 px-4 sm:px-8 bg-[#020617] text-white overflow-hidden relative">
      
      {/* --- Ambient Background Effects --- */}
      <div className="absolute top-[-10%] left-[20%] w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-[150px] pointer-events-none"></div>
      <div className="absolute bottom-[-10%] right-[10%] w-[500px] h-[500px] bg-purple-600/10 rounded-full blur-[150px] pointer-events-none"></div>
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/stardust.png')] opacity-20 pointer-events-none"></div>

      <div className="max-w-7xl mx-auto relative z-10">
        
        {/* --- Hero Section --- */}
        <div className="text-center space-y-6 mb-20 animate-in fade-in slide-in-from-bottom-8 duration-700">
          <div className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-slate-900 border border-slate-800 shadow-inner">
            <Zap size={16} className="text-amber-400 fill-amber-400 animate-pulse" />
            <span className="text-xs font-black uppercase tracking-widest text-slate-300">Boost Your Productivity</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-black uppercase italic tracking-tighter">
            Academic <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-indigo-500 to-purple-500">Arsenal</span>
          </h1>
          
          <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto font-medium">
            Work smarter, not harder. Leverage our cutting-edge tools to automate boring tasks, plan your future, and dominate your exams.
          </p>
        </div>

        {/* --- Tools Grid --- */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {tools.map((tool, index) => (
            <Link 
              to={tool.link} 
              key={tool.id}
              className={`group relative bg-slate-900/40 backdrop-blur-xl border border-slate-800/80 rounded-[32px] p-8 transition-all duration-500 hover:-translate-y-4 overflow-hidden ${tool.shadow}`}
              style={{ animationDelay: `${index * 150}ms` }}
            >
              {/* Card Hover Glow Background */}
              <div className={`absolute inset-0 opacity-0 transition-opacity duration-500 ${tool.glow}`}></div>
              
              {/* Animated Top Border */}
              <div className={`absolute top-0 left-1/4 right-1/4 h-[2px] bg-gradient-to-r from-transparent via-white to-transparent opacity-0 group-hover:opacity-100 scale-x-0 group-hover:scale-x-100 transition-all duration-700`}></div>

              <div className="relative z-10 flex flex-col h-full">
                {/* Header: Icon & Badge */}
                <div className="flex justify-between items-start mb-8">
                  <div className={`w-16 h-16 rounded-2xl flex items-center justify-center bg-gradient-to-br ${tool.color} shadow-lg group-hover:scale-110 group-hover:rotate-3 transition-transform duration-500`}>
                    {React.cloneElement(tool.icon, { className: 'text-white drop-shadow-md' })}
                  </div>
                  <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider border ${tool.badgeColor}`}>
                    {tool.badge}
                  </span>
                </div>

                {/* Content */}
                <div className="flex-grow space-y-4">
                  <h2 className="text-2xl font-black text-white tracking-tight group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-slate-400 transition-colors">
                    {tool.title}
                  </h2>
                  <p className="text-slate-400 text-sm leading-relaxed font-medium">
                    {tool.description}
                  </p>
                </div>

                {/* Action Footer */}
                <div className="mt-8 pt-6 border-t border-slate-800/50 flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-500 uppercase tracking-widest group-hover:text-white transition-colors">Launch Tool</span>
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center bg-slate-800 group-hover:bg-gradient-to-r ${tool.color} transition-all duration-500`}>
                    <ChevronRight size={18} className="text-slate-400 group-hover:text-white group-hover:translate-x-1 transition-all" />
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>

        {/* --- Inspirational Motivation Section --- */}
        <div className="mt-32 relative rounded-[40px] border border-indigo-500/20 bg-gradient-to-br from-indigo-900/20 to-slate-900/50 backdrop-blur-2xl p-10 md:p-16 overflow-hidden">
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-10"></div>
          
          <div className="relative z-10 grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div className="space-y-6">
              <h3 className="text-3xl md:text-5xl font-black italic uppercase tracking-tighter">
                Why use our <span className="text-indigo-400">Ecosystem?</span>
              </h3>
              <p className="text-slate-400 text-lg leading-relaxed">
                University life is chaotic. Between assignments, labs, and career planning, time is your most valuable asset. Our tools are designed to automate the grind so you can focus on actual learning and skill development.
              </p>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-6 rounded-3xl bg-slate-950/50 border border-slate-800 flex items-start gap-4">
                <Clock className="text-amber-400 mt-1" size={24} />
                <div>
                  <h4 className="font-bold text-white mb-1">Save 10+ Hours</h4>
                  <p className="text-xs text-slate-500">Stop formatting PDFs. Let the system do it instantly.</p>
                </div>
              </div>
              <div className="p-6 rounded-3xl bg-slate-950/50 border border-slate-800 flex items-start gap-4">
                <Target className="text-emerald-400 mt-1" size={24} />
                <div>
                  <h4 className="font-bold text-white mb-1">Stay on Track</h4>
                  <p className="text-xs text-slate-500">Know exactly what CGPA you need to hit your goals.</p>
                </div>
              </div>
              <div className="p-6 rounded-3xl bg-slate-950/50 border border-slate-800 flex items-start gap-4 sm:col-span-2">
                <ShieldCheck className="text-blue-400 mt-1" size={24} />
                <div>
                  <h4 className="font-bold text-white mb-1">100% Reliable & Secure</h4>
                  <p className="text-xs text-slate-500">Your academic data is encrypted and used only to give you the best personalized output.</p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default ToolsPage;